[build]
command = "pnpm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Stellar Contracts

[[redirects]]
from = "/stellar-contracts/0.4.0/*"
to = "/stellar-contracts/:splat"
status = 301

[[redirects]]
from = "/stellar-contracts/0.1.0/*"
to = "/stellar-contracts/:splat"
status = 301

# Contracts Cairo

[[redirects]]
from = "/contracts-cairo/3.0.0/*"
to = "/contracts-cairo/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/3.0.0-alpha.2/*"
to = "/contracts-cairo/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/3.0.0-alpha.1/*"
to = "/contracts-cairo/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/2.0.0-alpha.1/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/2.0.0-alpha.1/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.20.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.20.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.19.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.19.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.18.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.18.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.17.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.17.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.16.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.16.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.15.1/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.15.1/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.15.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.15.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.14.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.14.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.13.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.13.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.12.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.12.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.11.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.11.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/0.10.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/0.10.0/:splat"
status = 301

[[redirects]]
from = "/contracts-cairo/1.0.0/*"
to = "https://old-docs.openzeppelin.com/contracts-cairo/1.0.0/:splat"
status = 301

# Community Contracts

[[redirects]]
from = "/community-contracts/0.0.1/*"
to = "/community-contracts/:splat"
status = 301

# Midnight Compact

[[redirects]]
from = "/contracts-compact/0.0.1/*"
to = "/community-contracts/:splat"
status = 301

# Stylus

[[redirects]]
from = "/contracts-stylus/0.3.0/*"
to = "/contracts-stylus/:splat"
status = 301

# Polkadot Substrate Runtimes

[[redirects]]
from = "/substrate-runtimes/3.0.0-rc/*"
to = "/substrate-runtimes/:splat"
status = 301

# Uniswap Hooks

[[redirects]]
from = "/uniswap-hooks/1.x/*"
to = "/uniswap-hooks/:splat"
status = 301

# Zama Confidential contracts

[[redirects]]
from = "/confidential-contracts/0.2/*"
to = "/confidential-contracts/:splat"
status = 301

# Tools redirects

[[redirects]]
from = "/subgraphs/0.1.x/*"
to = "/contracts/5.x/subgraphs/:splat"
status = 301

[[redirects]]
from = "/monitor/1.0.x/*"
to = "/monitor/:splat"
status = 301

[[redirects]]
from = "/monitor/0.2.x/*"
to = "/monitor/:splat"
status = 301

[[redirects]]
from = "/monitor/0.1.0/*"
to = "/monitor/:splat"
status = 301

[[redirects]]
from = "/relayer/1.1.x/*"
to = "/relayer/:splat"
status = 301

[[redirects]]
from = "/relayer/1.0.x/*"
to = "/relayer/:splat"
status = 301

[[redirects]]
from = "/relayer/0.2.x/*"
to = "/relayer/:splat"
status = 301

[[redirects]]
from = "/relayer/0.1.0/*"
to = "/relayer/:splat"
status = 301

[[redirects]]
from = "/relayer/0.1.x/*"
to = "/relayer/:splat"
status = 301

[[redirects]]
from = "/contracts-ui-builder/1.0.x/*"
to = "/contracts-ui-builder/:splat"
status = 301

[[redirects]]
from = "/learn/*"
to = "/contracts/5.x/learn/:splat"
status = 301

# Deprecated projects redirects
[[redirects]]
from = "/cli/*"
to = "/"
status = 301

[[redirects]]
from = "/network-js/*"
to = "/"
status = 301

[[redirects]]
from = "/nile/*"
to = "/"
status = 301

[[redirects]]
from = "/test-environment/*"
to = "/"
status = 301

[[redirects]]
from = "/test-helpers/*"
to = "/"
status = 301

[[redirects]]
from = "/gsn-helpers/*"
to = "/"
status = 301

[[redirects]]
from = "/gsn-provider/*"
to = "/"
status = 301

[[redirects]]
from = "/starter-kits/*"
to = "/"
status = 301
